development:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: plain
  :user_name: davespace@me.com
  :password: ggLPn1Wb9FP6uGx6Wop9aA
  :enable_starttls_auto: true
production:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: plain
  :user_name: davespace@me.com
  :password: ggLPn1Wb9FP6uGx6Wop9aA
  :enable_starttls_auto: true